### ISSUE TITLE
App

### ISSUE THREAD

**Issue by sindresorhus** [rakuten-frontend/bower-browser#3]
I think this could be nice as an [atom-shell](https://github.com/atom/atom-shell) wrapped app.

That way users without any terminal experience could use Bower.

You could show a list of recent project, and let the user browse for existing ones. Would also go hand in hand with #2.

**Comment by htanjo** [comment]
Actually we have been developing a stand-alone app based on [node-webkit](https://github.com/nwjs/nw.js).

**rff-gui**
https://github.com/rakuten-frontend/rff-gui

But the rff-gui app wraps too many features and we're breaking up to more specific tools now.
This bower-browser is one of the spinoff.

Currently I'm not planning to make bower-browser itself stand-alone. But I'll talk to my team members.
Thank you!
